
import React, { useState } from 'react';
import { Button } from "../../components/ui/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "../../components/ui/card";
import { Textarea } from "../../components/ui/textarea";
import { Label } from "../../components/ui/label";
import { Slider } from "../../components/ui/slider";
import { Alert, AlertDescription, AlertTitle } from "../../components/ui/alert";
import { Loader2, AlertTriangle, Speaker, Download } from 'lucide-react';
import { useInvokeFunction } from '@/lib/supabase-functions';

// --- Placeholder for the backend function call ---
// This function needs to be connected to the actual edge function
// Example: Use invokeFunction('elevenLabsTTS', { body: { text, ... } })
async function generateSpeech({ text, stability, similarityBoost }) {
  // This is a mock implementation for UI development and will be replaced
  // by the platform's backend function call mechanism.
  console.log("Mocking backend call 'generateSpeech' with:", { text, stability, similarityBoost });

  if (!text || text.trim() === '') {
    throw new Error("Text input cannot be empty.");
  }
  if (text.length > 2500) {
      throw new Error("Text cannot exceed 2500 characters.");
  }
  
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  // Simulate an error if text contains 'error'
  if (text.toLowerCase().includes('error')) {
      throw new Error("Mock Error: Failed to generate speech from ElevenLabs.");
  }

  // Simulate missing credentials error
  if (text.toLowerCase().includes('secret')) {
      throw new Error("Mock Error: ELEVENLABS_API_KEY is not set in workspace secrets.");
  }

  // This is a placeholder for a short, silent MP3 file encoded in base64.
  // In a real implementation, the backend would return a much larger string.
  const sampleAudioBase64 = "data:audio/mpeg;base64,SUQzBAAAAAABEVRYWFgAAAAtAAADY29tbWVudABCaWdTb3VuZEJhbmsuY29tIC8gTGFTb25vdGhlcXVlLm9yZwBURU5DAAAAHQAAA1N3aXRjaCBQbHVzIMKpIE5DSCBTb2Z0d2FyZQBUSVQyAAAABgAAAzIyMzUAVFNTRQAAAAgAAANMYXZmNTUuMwA=";
  return { audio: sampleAudioBase64 };
}
// --- End of placeholder ---


export default function TextToSpeechPage() {
  const invokeFunction = useInvokeFunction();

  const [text, setText] = useState('Hello! I am a realistic voice generated by artificial intelligence. You can adjust my stability and similarity to change how I sound.');
  const [stability, setStability] = useState(0.5);
  const [similarityBoost, setSimilarityBoost] = useState(0.7);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [audioUrl, setAudioUrl] = useState(null);

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    setAudioUrl(null);

    try {
      if (text.length > 2500) {
        throw new Error("Text cannot be longer than 2500 characters.");
      }
      const { audio } = await generateSpeech({ text, stability, similarityBoost });
      setAudioUrl(audio);
    } catch (e) {
      setError(e.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8 max-w-2xl mx-auto">
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="text-2xl">ElevenLabs Text-to-Speech</CardTitle>
          <CardDescription>Convert text into realistic speech. Make sure your API Key and Voice ID are set in your workspace secrets.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="text-input">Text to Convert</Label>
            <Textarea
              id="text-input"
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Enter text here..."
              rows={6}
              maxLength={2500}
              className="resize-none"
            />
            <p className="text-xs text-slate-500 text-right">{text.length} / 2500</p>
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <Label htmlFor="stability">Stability</Label>
                <span className="text-sm text-slate-600">{stability.toFixed(2)}</span>
              </div>
              <Slider
                id="stability"
                min={0}
                max={1}
                step={0.01}
                value={[stability]}
                onValueChange={(value) => setStability(value[0])}
              />
              <p className="text-xs text-slate-500">More consistent vs. more expressive speech.</p>
            </div>
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <Label htmlFor="similarity">Similarity Boost</Label>
                <span className="text-sm text-slate-600">{similarityBoost.toFixed(2)}</span>
              </div>
              <Slider
                id="similarity"
                min={0}
                max={1}
                step={0.01}
                value={[similarityBoost]}
                onValueChange={(value) => setSimilarityBoost(value[0])}
              />
              <p className="text-xs text-slate-500">Higher values boost similarity to the original voice.</p>
            </div>
          </div>

          {error && (
            <Alert variant="destructive">
              <AlertTriangle className="h-4 w-4" />
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {audioUrl && (
            <div className="space-y-3">
              <Label>Generated Audio</Label>
              <div className="flex items-center gap-4 p-3 bg-slate-50 rounded-lg">
                <audio src={audioUrl} controls className="w-full" />
                <a href={audioUrl} download="generated_speech.mp3">
                  <Button variant="outline" size="icon">
                    <Download className="h-4 w-4" />
                  </Button>
                </a>
              </div>
            </div>
          )}

        </CardContent>
        <CardFooter>
          <Button onClick={handleGenerate} disabled={isLoading} className="w-full pwru-button-primary">
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Speaker className="mr-2 h-4 w-4" />
                Generate Speech
              </>
            )}
          </Button>
        </CardFooter>
      </Card>
    </div>
  );
}
